### ISSUE TITLE
HardwareSerial1 in Arduino Leonardo

### ISSUE THREAD

**Issue by khseal** [strange-v/MHZ19#1]
Hi want to use the second port in arduino leonardo.
His name is serial1.
I do not understand how to initialize it correctly.

**Comment by strange-v** [comment]
Use
`MHZ19 mhz(&Serial1);`

I've added "sw_get_values" example.

**Comment by khseal** [comment]
I tried this option. After that, arduino became an unknown device .. =)
I had to catch the bootloader at the reset to restore arduino.

**Comment by strange-v** [comment]
It's quite weird.
Unfortunately I don't have Arduino Leonardo, but I've used this lib with hardware serial on Arduino Mega without any issues.
Probably you could check Serial1 with FTDI adapter to be sure that it works.

**Comment by khseal** [comment]
It works exactly with the other code, and with your library this is the problem = (

**Comment by strange-v** [comment]
Please provide the complete sketch/code which you use to reproduce the problem.

**Comment by khseal** [comment]
![image](https://user-images.githubusercontent.com/11374629/33178490-66b70d3a-d077-11e7-9780-659fac5bbd6d.png)
You can see the message that the device is unknown.

**Comment by strange-v** [comment]
There was a typo in the data reading, fixed.
Also interfaces was updated to be less confusing (see examples).
