### ISSUE TITLE
MHZ19PWM doesn't work on the latest ESP releases

### ISSUE THREAD

**Issue by strange-v** [strange-v/MHZ19#9]
MHZ19PWM doesn't work on the latest ESP8266 and probably ESP32 releases.
Check IRAM ISR attributes and other stuff.

**Comment by Di-Strix** [comment]
Hello! I created a pull request #11 from my forked branch in which I fixed problems with esp boards. Please check it out

**Comment by strange-v** [comment]
@Di-Strix, thanks! I've always postponed this task.
I'll check it soon.

**Comment by strange-v** [comment]
Fixed by @Di-Strix.
